name: 算法前端配置界面发布

on:
  push:
#    tags:
#      - AlgorithmConfigUI*

jobs:
#  release:
#    name: ${{ matrix.os }} 创建Release
#    runs-on:  ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
#    steps:
#      - name: 克隆代码
#        uses: actions/checkout@v3
#      - name: 创建发行版本
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body_path: README.md
#          draft: false
#          prerelease: false
#  windows:
#    name: 打包发布 (${{ matrix.os }},${{ matrix.architecture}},${{ matrix.python-version }})
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ "windows-latest" ] #, "macos-latest", "windows-latest"
#        architecture: [ "x86" ]
#        python-version: [ "3.6" ]
#    steps:
#      - name: 克隆代码
#        uses: actions/checkout@v3
#      - name: 安装Conda环境
#        uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
#          architecture: ${{ matrix.architecture}}
#          miniconda-version: "latest"
#      - name: Windows准备打包环境
#        shell: pwsh
#        run: |
#          pip install pywin32
#          pip install -r requirements.txt
#      - name: 编译打包
#        shell: pwsh
#        run: |
#          python packing.py
#      - name: 压缩
#        shell: pwsh
#        run: |
#          7z a -tzip .\${{runner.os}}.zip   .\releases\*\${{runner.os}}\
#          ls
#      ## 发布
#      - name: 发布
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: "Windows.zip"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  other:
    name: 打包发布 (${{ matrix.os }},${{ matrix.architecture}},${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-18.04"] #, "macos-latest", "windows-latest"
        architecture: ["x64"]
        python-version: ["3.6"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: jadehh/AlgorithmConfigUI
          path: AlgorithmConfigUI
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
#      - name: 安装Conda环境
#        uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
#          architecture: ${{ matrix.architecture}}
#          miniconda-version: "latest"

#      - name: 准备打包环境
#        shell: pwsh
#        run: |
#          pip install -r requirements.txt
#      - name: MacOS打包
#        shell: pwsh
#        if: runner.os == 'macOS'
#        run: |
#          python packing.py
#          ls -l
#          cd releases
#          ls -l
#      - name: Linux打包
#        shell: pwsh
#        if: runner.os == 'Linux'
#        run: |
#          wget https://github.com/jadehh/jadehh_file/releases/download/conta_captureV2.4.8.7/appimagetool-x86_64.AppImage
#          mv appimagetool-x86_64.AppImage ~/
#          chmod a+x ~/appimagetool-x86_64.AppImage
#          python packing.py
#      - name: 压缩
#        shell: pwsh
#        run: |
#          zip -r ${{runner.os}}.zip  releases/*/${{runner.os}}/
#      ## 发布
#      - name: 发布
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: ${{runner.os}}.zip
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}