name: 箱号服务发布

on:
  push:
#    tags:
#      - conta_serviceV*

jobs:
#  release:
#    name: ${{ matrix.os }} 创建Release
#    runs-on:  ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
#    steps:
#      - name: 克隆代码
#        uses: actions/checkout@v3
#      - name: 创建发行版本
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body_path: README.md
#          draft: false
#          prerelease: false
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - x64
    steps:
      - name: 查看系统环境
        shell: pwsh
        run: |
          uname -a
