name: 箱号图片抓拍定制版发布

on:
  push:
    tags:
      - conta_capture_customV*

jobs:
  release:
    name: 箱号图片抓拍定制版发布
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
    steps:
      - name: 克隆代码
        uses: actions/checkout@v3
      - name: 创建发行版本
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false

  amd64_job:
    name:  ${{ matrix.device_type }}箱号图片抓拍定制版打包
    container:
      image: jadehh/container_ocr:amd64-packing-1.0.1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
        device_type: ["Paddle"]
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/ContainerOCR
          ref: conta_capture_custom
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 安装pip环境
        run: pip install -r code/requirements.txt
      - name: Paddle打包编译
        if: ${{ matrix.device_type=='Paddle'}}
        run: |
          cd code
          python packing_app.py \
                --head_str "import sys\nsys.path.append('/usr/local/conta_detect-1.0/python_lib')\nimport paddle\n" \
                --is_exec False
   # 发布
      - name: 发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            "./code/Output/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 给最高的权限

