name: 箱号服务发布

on:
  push:
#    tags:
#      - conta_serviceV*
#
jobs:
#  release:
#    name: ${{ matrix.os }} 箱号服务发布
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
#    steps:
#      - name: 克隆代码
#        uses: actions/checkout@v3
#      - name: 创建发行版本
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body_path: README.md
#          draft: false
#          prerelease: false
  Linux_Amd64:
    name: ${{ matrix.os }} 箱号服务打包
    runs-on: ubuntu-latest
    steps:
      - name: 准备Python环境
        uses: actions/setup-python@v3
        with:
          python-version: 3.6.9
      - name: 测试Python环境
        run: Python -V
#      - name: 下载代码
#        uses: actions/checkout@v3
#        with:
#          repository: jadehh/ContainerOCR
#          ref: 箱号服务
#          path: code
#          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
#      - name: 安装pip环境
#        run: pip install -r code/requirements.txt
#
#      - name: 打包编译
#        run: |
#          cd code
#          python packing_app.py \
#                 --extra_sys_str /usr/local/conta_detect-1.0/python_lib \
#                 --name 箱号服务

#      - name: 查看是否打包编译完成
#        run: |
#          cd code/Output
#          ls -l
#
#      - name: 发布
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files:
#            "code/Output/*"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 给最高的权限
