name: 算法前端配置界面发布

on:
  push:
    tags:
      - AlgorithmConfiureV*

jobs:
  release:
    name: ${{ matrix.os }} 创建Release
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
    steps:
      - name: 克隆代码
        uses: actions/checkout@v3
      - name: 创建发行版本
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false
  Ubuntu:
    name: 打包发布-操作系统版本:(${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: jadehh/container_ocr:amd64-packing-1.0.1
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] # "ubuntu-18.04", "windows-latest","macos-latest"
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/AlgorithmConfigUI
          ref: AlgorithmConfiure
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 准备打包环境
        shell: pwsh
        run: |
          pip install -r code/requirements.txt
          apt-get install -y wget
          apt-get install -y libgl1-mesa-glx
          apt-get install -y libsm6 libxrender1 libfontconfig1
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage ~/
      - name: 编译打包
        env:
          PYTHONIOENCODING: "utf-8"
        shell: pwsh
        run: |
          cd code
          python packing.py   # --specify_files samplesMain.py
      - name: 测试是否打包完成
        shell: pwsh
        run: |
          cd code/Output
          ls
      # 发布
      - name: 发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            "./code/Output/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 给最高的权限

