name: 箱号服务发布

on:
  push:
#    tags:
#      - conta_serviceV*

jobs:
  release:
    name: ${{ matrix.os }} 箱号服务发布
    runs-on: ubuntu-latest
    container:
      image: python:3.6.9
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/ContainerOCR
          ref: 箱号服务
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 安装pip环境
        run: pip install -r code/requirements.txt

      - name: 打包编译
        run: |
          cd code
          python packing_app.py

      - name: 查看是否打包编译完成
        run: |
          cd code
          ls -l
