name: 箱号服务发布

on:
  push:
#    tags:
#      - conta_serviceV*

jobs:
  release:
    name: ${{ matrix.os }} 箱号服务发布
    runs-on: ubuntu-latest
    container:
      image: python:3.6.9
      env:
        NODE_ENV: development
      volumes:
        - /home/runner:/root/jade
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/ContainerOCR
          ref: 箱号服务
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 安装pip环境
        run: pip install code/requirements.txt
